# -*- coding: utf-8 -*-
"""Enterprise Operation analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgWwTv0W6Xi6Zp9XHhzxjXDalPgw1vsf
"""

from google.colab import files
import io

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

from google.colab import files
import io

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

import pandas as pd

df = pd.read_csv("tickets.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

df.info()

#convert datatypes
# Convert date column
df["Created_Date"] = pd.to_datetime(df["Created_Date"])

# Convert Boolean columns
df["SLA_Breached"] = df["SLA_Breached"].map({
    "True": True,
    "False": False
})

df["Escalation_Flag"] = df["Escalation_Flag"].map({
    "True": True,
    "False": False
})

# Check the updated data types
df.dtypes

print("SLA_Breached values:")
print(df["SLA_Breached"].value_counts(dropna=False))

print("\nEscalation_Flag values:")
print(df["Escalation_Flag"].value_counts(dropna=False))

# Reload the original CSV to restore the columns
df = pd.read_csv("tickets.csv")

print("SLA_Breached:")
print(df["SLA_Breached"].value_counts(dropna=False))

print("\nEscalation_Flag:")
print(df["Escalation_Flag"].value_counts(dropna=False))

# Convert date
df["Created_Date"] = pd.to_datetime(df["Created_Date"])

# Convert Yes/No columns to Boolean
df["SLA_Breached"] = df["SLA_Breached"].map({
    "Yes": True,
    "No": False
})

df["Escalation_Flag"] = df["Escalation_Flag"].map({
    "Yes": True,
    "No": False
})

# Check the result
print(df[["Created_Date", "SLA_Breached", "Escalation_Flag"]].dtypes)

#check missing values
missing = df.isnull().sum()

missing_summary = pd.DataFrame({
    "Missing_Values": missing,
    "Missing_Percentage": (missing / len(df) * 100).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing_Values"] > 0
].sort_values("Missing_Values", ascending=False)

missing_summary

#filling missing categorical columns
df["Root_Cause_Clean"] = df["Root_Cause"].fillna("Unknown")
df["Customer_Impact_Clean"] = df["Customer_Impact"].fillna("Unknown")

# Check the result
print("Root Cause:")
print(df["Root_Cause_Clean"].value_counts())

print("\nCustomer Impact:")
print(df["Customer_Impact_Clean"].value_counts())

#Descriptive statistics
df[[
    "Resolution_Hours",
    "SLA_Hours",
    "Risk_Score"
]].describe().round(2)

#Investigate resolution-time outliers
df["Resolution_Hours"].quantile([0.90, 0.95, 0.99, 0.995, 1.00])

#resolution-time distribution.
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.hist(df["Resolution_Hours"], bins=50)

plt.title("Distribution of Resolution Time")
plt.xlabel("Resolution Hours")
plt.ylabel("Number of Tickets")

plt.show()

#Compare resolution time by risk category
risk_resolution = (
    df.groupby("Risk_Category")["Resolution_Hours"]
      .agg(["count", "mean", "median"])
      .round(2)
)

risk_resolution

#visualisation of resolution time by risk category
risk_resolution["mean"].sort_values().plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Average Resolution Time by Risk Category")
plt.xlabel("Risk Category")
plt.ylabel("Average Resolution Hours")
plt.xticks(rotation=0)

plt.show()

#Calculate SLA compliance by risk category
risk_sla = (
    df.groupby("Risk_Category")
      .agg(
          total_tickets=("Ticket_ID", "count"),
          sla_breaches=("SLA_Breached", "sum")
      )
)

risk_sla["sla_compliance_pct"] = (
    (1 - risk_sla["sla_breaches"] / risk_sla["total_tickets"]) * 100
).round(2)

risk_sla

#visualize SLA compliance by risk category
risk_sla["sla_compliance_pct"].sort_values().plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("SLA Compliance by Risk Category")
plt.xlabel("Risk Category")
plt.ylabel("SLA Compliance (%)")
plt.xticks(rotation=0)

plt.show()

#Analyze escalation vs resolution time
escalation_analysis = (
    df.groupby("Escalation_Flag")
      .agg(
          total_tickets=("Ticket_ID", "count"),
          avg_resolution_hours=("Resolution_Hours", "mean"),
          avg_risk_score=("Risk_Score", "mean"),
          sla_breaches=("SLA_Breached", "sum")
      )
      .round(2)
)

escalation_analysis["sla_compliance_pct"] = (
    (1 - escalation_analysis["sla_breaches"] /
     escalation_analysis["total_tickets"]) * 100
).round(2)

escalation_analysis

#visualize escalation vs resolution time
escalation_analysis["avg_resolution_hours"].plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Average Resolution Time: Escalated vs Not Escalated")
plt.xlabel("Escalation Status")
plt.ylabel("Average Resolution Hours")
plt.xticks(rotation=0)

plt.show()

#business unit analysis
business_unit_analysis = (
    df.groupby("Business_Unit_ID")
      .agg(
          total_tickets=("Ticket_ID", "count"),
          avg_resolution_hours=("Resolution_Hours", "mean"),
          sla_breaches=("SLA_Breached", "sum"),
          avg_risk_score=("Risk_Score", "mean"),
          escalations=("Escalation_Flag", "sum")
      )
      .round(2)
)

business_unit_analysis["sla_compliance_pct"] = (
    (1 - business_unit_analysis["sla_breaches"] /
     business_unit_analysis["total_tickets"]) * 100
).round(2)

business_unit_analysis

#Add business-unit names
business_unit_map = {
    1: "Customer Operations",
    2: "Quality Assurance",
    3: "Supply Chain",
    4: "Manufacturing",
    5: "Regulatory Affairs",
    6: "IT Operations",
    7: "Finance",
    8: "Commercial Operations"
}

business_unit_analysis = business_unit_analysis.reset_index()

business_unit_analysis["Business_Unit"] = (
    business_unit_analysis["Business_Unit_ID"].map(business_unit_map)
)

business_unit_analysis = business_unit_analysis[
    [
        "Business_Unit",
        "total_tickets",
        "avg_resolution_hours",
        "sla_compliance_pct",
        "avg_risk_score",
        "escalations"
    ]
].sort_values("sla_compliance_pct")

business_unit_analysis

#visualize SLA compliance by business unit.
business_unit_analysis.plot(
    x="Business_Unit",
    y="sla_compliance_pct",
    kind="bar",
    figsize=(10, 6),
    legend=False
)

plt.title("SLA Compliance by Business Unit")
plt.xlabel("Business Unit")
plt.ylabel("SLA Compliance (%)")
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

#Analyze SLA performance by priority
priority_analysis = (
    df.groupby("Priority")
      .agg(
          total_tickets=("Ticket_ID", "count"),
          avg_resolution_hours=("Resolution_Hours", "mean"),
          sla_breaches=("SLA_Breached", "sum"),
          avg_risk_score=("Risk_Score", "mean"),
          escalations=("Escalation_Flag", "sum")
      )
      .round(2)
)

priority_analysis["sla_compliance_pct"] = (
    (1 - priority_analysis["sla_breaches"] /
     priority_analysis["total_tickets"]) * 100
).round(2)

priority_analysis

#visualize  SLA performance by priority
priority_order = ["Critical", "High", "Medium", "Low"]

priority_analysis.loc[priority_order, "sla_compliance_pct"].plot(
    kind="bar",
    figsize=(8, 5),
    legend=False
)

plt.title("SLA Compliance by Ticket Priority")
plt.xlabel("Priority")
plt.ylabel("SLA Compliance (%)")
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

#Analyze monthly performance
monthly_analysis = (
    df.groupby(df["Created_Date"].dt.to_period("M"))
      .agg(
          total_tickets=("Ticket_ID", "count"),
          avg_resolution_hours=("Resolution_Hours", "mean"),
          sla_breaches=("SLA_Breached", "sum"),
          avg_risk_score=("Risk_Score", "mean")
      )
      .round(2)
)

monthly_analysis["sla_compliance_pct"] = (
    (1 - monthly_analysis["sla_breaches"] /
     monthly_analysis["total_tickets"]) * 100
).round(2)

monthly_analysis

#visualize monthly SLA performance trend
monthly_analysis["sla_compliance_pct"].plot(
    kind="line",
    figsize=(12, 6),
    marker="o"
)

plt.title("Monthly SLA Compliance Trend")
plt.xlabel("Month")
plt.ylabel("SLA Compliance (%)")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

#Analyze root causes
root_cause_analysis = (
    df.groupby("Root_Cause_Clean")
      .agg(
          total_tickets=("Ticket_ID", "count"),
          avg_resolution_hours=("Resolution_Hours", "mean"),
          sla_breaches=("SLA_Breached", "sum"),
          avg_risk_score=("Risk_Score", "mean"),
          escalations=("Escalation_Flag", "sum")
      )
      .round(2)
)

root_cause_analysis["sla_compliance_pct"] = (
    (1 - root_cause_analysis["sla_breaches"] /
     root_cause_analysis["total_tickets"]) * 100
).round(2)

root_cause_analysis.sort_values(
    "sla_compliance_pct"
)

#visualize rootcause SLA performance
root_cause_analysis.sort_values(
    "sla_compliance_pct"
)["sla_compliance_pct"].plot(
    kind="bar",
    figsize=(10, 6),
    legend=False
)

plt.title("SLA Compliance by Root Cause")
plt.xlabel("Root Cause")
plt.ylabel("SLA Compliance (%)")
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

#Find the top operational hotspots
# Mapping tables from our project dataset
process_map = {
    1: "Order Management",
    2: "Quality Review",
    3: "Inventory Planning",
    4: "Production Support",
    5: "Submission Management",
    6: "System Access",
    7: "Invoice Processing",
    8: "Customer Support"
}

df["Business_Unit"] = df["Business_Unit_ID"].map(business_unit_map)
df["Process"] = df["Process_ID"].map(process_map)

hotspots = (
    df.groupby(["Business_Unit", "Process"])
      .agg(
          total_tickets=("Ticket_ID", "count"),
          avg_resolution_hours=("Resolution_Hours", "mean"),
          sla_breaches=("SLA_Breached", "sum"),
          avg_risk_score=("Risk_Score", "mean"),
          escalations=("Escalation_Flag", "sum")
      )
      .round(2)
)

hotspots["sla_compliance_pct"] = (
    (1 - hotspots["sla_breaches"] /
     hotspots["total_tickets"]) * 100
).round(2)

hotspots = hotspots.reset_index().sort_values(
    ["sla_compliance_pct", "avg_resolution_hours"],
    ascending=[True, False]
)

hotspots.head(10)

#correlation analysis
correlation_matrix = df[
    [
        "Resolution_Hours",
        "SLA_Hours",
        "Risk_Score"
    ]
].corr().round(2)

correlation_matrix

#SLA Hours ↔ Risk Score visualisation
plt.figure(figsize=(8, 6))

plt.scatter(
    df["SLA_Hours"],
    df["Risk_Score"],
    alpha=0.15
)

plt.title("SLA Target vs Risk Score")
plt.xlabel("SLA Hours")
plt.ylabel("Risk Score")

plt.tight_layout()
plt.show()

#identify the most important KPIs
kpi_summary = pd.DataFrame({
    "Metric": [
        "Total Tickets",
        "Average Resolution Hours",
        "SLA Compliance",
        "SLA Breach Rate",
        "Average Risk Score",
        "Escalated Tickets",
        "Escalation Rate"
    ],
    "Value": [
        len(df),
        round(df["Resolution_Hours"].mean(), 2),
        round((~df["SLA_Breached"]).mean() * 100, 2),
        round(df["SLA_Breached"].mean() * 100, 2),
        round(df["Risk_Score"].mean(), 2),
        int(df["Escalation_Flag"].sum()),
        round(df["Escalation_Flag"].mean() * 100, 2)
    ]
})

kpi_summary

#dataset for Power BI
df.to_csv("enterprise_operations_risk_analytics_clean.csv", index=False)

print("Cleaned dataset exported successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

